### ISSUE TITLE
我曾经也研究过用golang 重写 fluentd

### ISSUE THREAD

**Issue by lostz** [hnlq715/gofluent#2]
我过了一遍你的代码
fluentd 安装依赖确实是一个很大的痛点.但是其实fluentd 有个更大的问题就是收集中心是单点,官方有个golang 版本的forward,我现在的实现和你很像,但是我直接使用nats-io的gnats集成代码中,避免了代码问题,而且本身gnatsd作为消息系统性能就特别强悍.我决定你可以看一下,我当初看过fluentd 的ruby 源码,其中他本身实现了tail -f 功能,实现很巧妙.并不是使用inotify,我看你使用的那个tail 的golang,源码我读过,我记得如果有lograoted的话,好像tail 就失效了,具体我忘记了,你可以看一下fluetnd 的源码,可以把这地方改一下.

**Comment by sysulq** [comment]
谢谢。
fluentd的问题很多，尤为严重的是协议设计问题，所以在gofluent里面也做了很多tradeoff，譬如forward给fluentd时，每次发送都重新建立了一个连接，因为当时不支持response，客户端无法确认fluentd是否正确处理该消息。

我当初也仔细研究过fluentd的源码，你提到的tail -f功能，如果我没有记错，它应该是用poll的方式实现的。而我这里用到的tail库，实际上支持poll和inotify两种形式。是的，inotify当时确实存在你说的这个问题，所以我选择了poll方式，不过我现在不确定inotify是否已经fix这个问题。

再者，你提到的gnats应该是个不错的选择。不过如果让我现在来选型的话，我可能更乐意考虑ELK：）
